services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27007:27017"
      # - "outer_port:inner_port"
    volumes:
      - ./mongodb:/data/db
      # - ./host_path:container_path
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  mongodb:
    